### PR TITLE
Update onerror.test.js

### PR DESCRIPTION
**Pull request by anton-piliugin**

### CODE REVIEW

**Comment by vitalets** [comment]
Hi Could you explain why this is needed?

**Comment by anton-piliugin** [comment]
Test not passed without done()

**Comment by vitalets** [comment]
> Test not passed without done()

If promise is returned from test done() callback is not needed.

**Comment by anton-piliugin** [comment]
Is it normal that your original code (without done() callback) doesn't pass the test? Just asking. Thank you

**Comment by vitalets** [comment]
> Is it normal that your original code (without done() callback) doesn't pass the test? Just asking. Thank you

Just checked on master - all tests are passing.
```
  onError
    ✓ should trigger for incorrect urls (175ms)
    - should trigger by server error
```

Could you show the error output and info about your env?

**Comment by anton-piliugin** [comment]
ERROR: ` onError
    1) should trigger for incorrect urls
    - should trigger by server error
1) onError
       should trigger for incorrect urls:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\xampp\htdocs\v2\websocket-as-promised-master\test\specs\onerror.test.js)`
ENV: `{ ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\secret\\AppData\\Roaming',
  ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
  ChocolateyLastPathUpdate: 'Чт ноя  8 01:26:18 2018',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'secret',
  ComSpec: 'C:\\Windows\\system32\\cmd.exe',
  CUDA_PATH:
   'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0',
  CUDA_PATH_V9_0:
   'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0',
  DokanLibrary1: 'C:\\Program Files\\Dokan\\Dokan Library-1.2.1\\',
  DokanLibrary1_LibraryPath_x64: 'C:\\Program Files\\Dokan\\Dokan Library-1.2.1\\lib\\',
  DokanLibrary1_LibraryPath_x86: 'C:\\Program Files\\Dokan\\Dokan Library-1.2.1\\x86\\lib\\',
  DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
  FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
  FPS_BROWSER_USER_PROFILE_STRING: 'Default',
  HOME: 'C:\\Users\\secret',
  HOMEDRIVE: 'C:',
  HOMEPATH: '\\Users\\secret',
  INIT_CWD: 'C:\\xampp\\htdocs\\v2\\websocket-as-promised-master',
  INTEL_DEV_REDIST:
   'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\',
  LOADED_MOCHA_OPTS: 'true',
  LOCALAPPDATA: 'C:\\Users\\secret\\AppData\\Local',
  LOGONSERVER: '\\\\secret',
  MIC_LD_LIBRARY_PATH:
   'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\compiler\\lib\\mic',
  MOZ_PLUGIN_PATH:
   'C:\\PROGRAM FILES (X86)\\FOXIT SOFTWARE\\FOXIT READER\\plugins\\',
  NODE: 'C:\\Program Files\\nodejs\\node.exe',
  NODE_EXE: 'C:\\Program Files\\nodejs\\\\node.exe',
  NPM_CLI_JS:
   'C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js',
  npm_config_access: '',
  npm_config_allow_same_version: '',
  npm_config_also: '',
  npm_config_always_auth: '',
  npm_config_argv:
   '{"remain":[],"cooked":["run","test"],"original":["run","test"]}',
  npm_config_audit: 'true',
  npm_config_audit_level: 'low',
  npm_config_auth_type: 'legacy',
  npm_config_bin_links: 'true',
  npm_config_browser: '',
  npm_config_ca: '',
  npm_config_cache: 'C:\\Users\\secret\\AppData\\Roaming\\npm-cache',
  npm_config_cache_lock_retries: '10',
  npm_config_cache_lock_stale: '60000',
  npm_config_cache_lock_wait: '10000',
  npm_config_cache_max: 'Infinity',
  npm_config_cache_min: '10',
  npm_config_cafile: '',
  npm_config_cert: '',
  npm_config_cidr: '',
  npm_config_color: 'true',
  npm_config_commit_hooks: 'true',
  npm_config_depth: 'Infinity',
  npm_config_description: 'true',
  npm_config_dev: '',
  npm_config_dry_run: '',
  npm_config_editor: 'notepad.exe',
  npm_config_engine_strict: '',
  npm_config_fetch_retries: '2',
  npm_config_fetch_retry_factor: '10',
  npm_config_fetch_retry_maxtimeout: '60000',
  npm_config_fetch_retry_mintimeout: '10000',
  npm_config_force: '',
  npm_config_git: 'git',
  npm_config_git_tag_version: 'true',
  npm_config_global: '',
  npm_config_globalconfig: 'C:\\Users\\secret\\AppData\\Roaming\\npm\\etc\\npmrc',
  npm_config_globalignorefile:
   'C:\\Users\\secret\\AppData\\Roaming\\npm\\etc\\npmignore',
  npm_config_global_style: '',
  npm_config_group: '',
  npm_config_ham_it_up: '',
  npm_config_heading: 'npm',
  npm_config_https_proxy: '',
  npm_config_if_present: '',
  npm_config_ignore_prepublish: '',
  npm_config_ignore_scripts: '',
  npm_config_init_author_email: '',
  npm_config_init_author_name: '',
  npm_config_init_author_url: '',
  npm_config_init_license: 'ISC',
  npm_config_init_module: 'C:\\Users\\secret\\.npm-init.js',
  npm_config_init_version: '1.0.0',
  npm_config_json: '',
  npm_config_key: '',
  npm_config_legacy_bundling: '',
  npm_config_link: '',
  npm_config_local_address: '',
  npm_config_loglevel: 'notice',
  npm_config_logs_max: '10',
  npm_config_long: '',
  npm_config_maxsockets: '50',
  npm_config_message: '%s',
  npm_config_metrics_registry: 'https://registry.npmjs.org/',
  npm_config_node_gyp:
   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
  npm_config_node_options: '',
  npm_config_node_version: '10.13.0',
  npm_config_noproxy: '',
  npm_config_offline: '',
  npm_config_onload_script: '',
  npm_config_only: '',
  npm_config_optional: 'true',
  npm_config_otp: '',
  npm_config_package_lock: 'true',
  npm_config_package_lock_only: '',
  npm_config_parseable: '',
  npm_config_prefer_offline: '',
  npm_config_prefer_online: '',
  npm_config_prefix: 'C:\\Users\\secret\\AppData\\Roaming\\npm',
  npm_config_preid: '',
  npm_config_production: '',
  npm_config_progress: 'true',
  npm_config_proxy: '',
  npm_config_python:
   'C:\\Users\\secret\\.windows-build-tools\\python27\\python.exe',
  npm_config_read_only: '',
  npm_config_rebuild_bundle: 'true',
  npm_config_registry: 'https://registry.npmjs.org/',
  npm_config_rollback: 'true',
  npm_config_save: 'true',
  npm_config_save_bundle: '',
  npm_config_save_dev: '',
  npm_config_save_exact: '',
  npm_config_save_optional: '',
  npm_config_save_prefix: '^',
  npm_config_save_prod: '',
  npm_config_scope: '',
  npm_config_scripts_prepend_node_path: 'warn-only',
  npm_config_script_shell: '',
  npm_config_searchexclude: '',
  npm_config_searchlimit: '20',
  npm_config_searchopts: '',
  npm_config_searchstaleness: '900',
  npm_config_send_metrics: '',
  npm_config_shell: 'C:\\Windows\\system32\\cmd.exe',
  npm_config_shrinkwrap: 'true',
  npm_config_sign_git_commit: '',
  npm_config_sign_git_tag: '',
  npm_config_sso_poll_frequency: '500',
  npm_config_sso_type: 'oauth',
  npm_config_strict_ssl: 'true',
  npm_config_tag: 'latest',
  npm_config_tag_version_prefix: 'v',
  npm_config_timing: '',
  npm_config_tmp: 'C:\\Users\\sec~1\\AppData\\Local\\Temp',
  npm_config_umask: '0000',
  npm_config_unicode: '',
  npm_config_unsafe_perm: 'true',
  npm_config_update_notifier: 'true',
  npm_config_usage: '',
  npm_config_user: '',
  npm_config_userconfig: 'C:\\Users\\secret\\.npmrc',
  npm_config_user_agent: 'npm/6.4.1 node/v10.13.0 win32 x64',
  npm_config_version: '',
  npm_config_versions: '',
  npm_config_viewer: 'browser',
  npm_execpath:
   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
  npm_lifecycle_event: 'test',
  npm_lifecycle_script: 'mocha test/setup.js test/specs',
  npm_node_execpath: 'C:\\Program Files\\nodejs\\node.exe',
  npm_package_author_email: 'noginsk@rambler.ru',
  npm_package_author_name: 'Vitaliy Potapov',
  npm_package_bugs_url: 'https://github.com/vitalets/websocket-as-promised/issues',
  npm_package_dependencies_chnl: '^0.4.2',
  npm_package_dependencies_flat_options: '^0.1.3',
  npm_package_dependencies_promise_controller: '^0.5.2',
  npm_package_dependencies_promise_prototype_finally: '^3.1.0',
  npm_package_description:
   'A WebSocket client library providing Promise-based API for connecting, disconnecting and messaging with server',
  npm_package_devDependencies_babel_loader: '^8.0.5',
  npm_package_devDependencies_babel_plugin_runtyper: '^0.4.0',
  npm_package_devDependencies_chai: '^4.2.0',
  npm_package_devDependencies_chai_as_promised: '^7.1.1',
  npm_package_devDependencies_eslint: '^5.13.0',
  npm_package_devDependencies_eslint_plugin_mocha: '^5.3.0',
  npm_package_devDependencies_get_port: '^4.1.0',
  npm_package_devDependencies_husky: '^1.3.1',
  npm_package_devDependencies_install_local: '^1.0.0',
  npm_package_devDependencies_jsdoc_to_markdown: '^4.0.1',
  npm_package_devDependencies_lint_staged: '^8.1.4',
  npm_package_devDependencies_mocha: '^5.2.0',
  npm_package_devDependencies_npm_run_all: '^4.1.5',
  npm_package_devDependencies_webpack: '^4.29.4',
  npm_package_devDependencies_webpack_cli: '^3.2.3',
  npm_package_devDependencies_websocket: '^1.0.28',
  npm_package_devDependencies__babel_cli: '^7.2.3',
  npm_package_devDependencies__babel_core: '^7.2.2',
  npm_package_devDependencies__babel_preset_env: '^7.3.1',
  npm_package_engines_node: '>=6',
  npm_package_homepage: 'https://github.com/vitalets/websocket-as-promised#readme',
  npm_package_husky_hooks_pre_commit: 'run-s lint-staged test',
  npm_package_husky_hooks_pre_push: 'run-s code test test-runtyper',
  npm_package_keywords_0: 'websocket',
  npm_package_keywords_1: 'websockets',
  npm_package_keywords_2: 'ws',
  npm_package_keywords_3: 'promise',
  npm_package_keywords_4: 'promise-api',
  npm_package_keywords_5: 'promises',
  npm_package_license: 'MIT',
  npm_package_lint_staged__src_test_______js: 'eslint',
  npm_package_main: 'dist/index.js',
  npm_package_name: 'websocket-as-promised',
  npm_package_readmeFilename: 'README.md',
  npm_package_repository_type: 'git',
  npm_package_repository_url: 'git://github.com/vitalets/websocket-as-promised.git',
  npm_package_scripts_build: 'webpack',
  npm_package_scripts_ci: 'run-s code test-dist test-runtyper',
  npm_package_scripts_code: 'npm run lint-all',
  npm_package_scripts_docs: 'node scripts/docs',
  npm_package_scripts_lint_all: 'eslint src test',
  npm_package_scripts_lint_staged: 'lint-staged',
  npm_package_scripts_postrelease: 'git push --follow-tags --no-verify',
  npm_package_scripts_prerelease: 'run-s code test-dist test-runtyper test-installed',
  npm_package_scripts_release: 'npm version $VER && npm publish',
  npm_package_scripts_release_minor: 'VER=minor npm run release',
  npm_package_scripts_release_patch: 'VER=patch npm run release',
  npm_package_scripts_test: 'mocha test/setup.js test/specs',
  npm_package_scripts_test_dist: 'npm run build && LIB_PATH=dist npm t',
  npm_package_scripts_test_installed:
   'node scripts/install-local && LIB_PATH=.installed/node_modules/websocket-as-promised npm t',
  npm_package_scripts_test_runtyper: 'RUNTYPER=1 npm run build && LIB_PATH=.runtyper npm t',
  npm_package_types: 'types/index.d.ts',
  npm_package_version: '0.9.0',
  NPM_PREFIX_NPM_CLI_JS:
   'C:\\Users\\secret\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
  NUMBER_OF_PROCESSORS: '8',
  NVCUDASAMPLES9_0_ROOT: 'C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v9.0',
  NVCUDASAMPLES_ROOT: 'C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v9.0',
  OneDrive: 'C:\\Users\\secret\\OneDrive',
  OS: 'Windows_NT',
  Path:
   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\npm-lifecycle\\node-gyp-bin;C:\\xampp\\htdocs\\v2\\websocket-as-promised-master\\node_modules\\.bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\libnvvp;C:\\Program Files\\Python36\\Scripts\\;C:\\Program Files\\Python36\\;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Users\\secret\\.windows-build-tools\\python27\\;C:\\Users\\secret\\.windows-build-tools\\python27\\Scripts;C:\\ProgramData\\Boxstarter;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\PuTTY\\;C:\\Users\\secret\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\CMake\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\flutter\\bin;C:\\Program Files\\dotnet\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Users\\secret\\.windows-build-tools\\python27\\;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\npm-lifecycle\\node-gyp-bin;C:\\Users\\secret\\AppData\\Roaming\\npm\\node_modules\\windows-build-tools\\node_modules\\.bin;C:\\Users\\secret\\AppData\\Roaming\\npm\\node_modules\\.bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\libnvvp;C:\\Program Files\\Python36\\Scripts\\;C:\\Program Files\\Python36\\;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Users\\secret\\.windows-build-tools\\python27\\;C:\\Users\\secret\\.windows-build-tools\\python27\\Scripts;C:\\ProgramData\\Boxstarter;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\PuTTY\\;C:\\Users\\secret\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\CMake\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\flutter\\bin;C:\\Program Files\\dotnet\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\npm-lifecycle\\node-gyp-bin;C:\\Users\\secret\\AppData\\Roaming\\npm\\node_modules\\windows-build-tools\\node_modules\\.bin;C:\\Users\\secret\\AppData\\Roaming\\npm\\node_modules\\.bin;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Users\\secret\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files (x86)\\Nmap;C:\\Python27\\libav;C:\\Python27\\swig;C:\\Users\\secret\\AppData\\Local\\atom\\bin;C:\\Users\\secret\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\secret\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\secret\\.dotnet\\tools;C:\\Users\\secret\\AppData\\Roaming\\npm;C:\\Program Files\\Java\\jdk-11.0.1\\bin;C:\\Users\\secret\\AppData\\Roaming\\Python\\Python36\\Scripts;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\extras\\CUPTI\\libx64',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.PY;.PYW',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
  PROCESSOR_LEVEL: '6',
  PROCESSOR_REVISION: '3c03',
  ProgramData: 'C:\\ProgramData',
  ProgramFiles: 'C:\\Program Files',
  'ProgramFiles(x86)': 'C:\\Program Files (x86)',
  ProgramW6432: 'C:\\Program Files',
  PROMPT: '$P$G',
  PSModulePath: ';',
  PUBLIC: 'C:\\Users\\Public',
  PYTHONPATH:
   'C:\\Users\\secret\\AppData\\Local\\Programs\\Python\\Python36-32\\',
  SESSIONNAME: 'Console',
  SystemDrive: 'C:',
  SystemRoot: 'C:\\Windows',
  TEMP: 'C:\\Users\\sec~1\\AppData\\Local\\Temp',
  TMP: 'C:\\Users\\sec~1\\AppData\\Local\\Temp',
  TMPDIR: 'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp',
  USERDOMAIN: 'secret',
  USERDOMAIN_ROAMINGPROFILE: 'secret',
  USERNAME: 'secret',
  USERPROFILE: 'C:\\Users\\secret',
  VS140COMNTOOLS:
   'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
  VS150COMCOMNTOOLS:
   'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\',
  windir: 'C:\\Windows' }`
* YOU CAN SEE THAT I UPDATED THE PACKAGES FOR YOUR PROJECT MAY BE THAT IS THE REASON OF THE ISSUE(?)

**Comment by frosty00** [comment]
fyi i checked and also get the same error with node v11.9.0 and npm 6.5.0

```
  65 passing (3s)
  1 pending
  1 failing

  1) onError
       should trigger for incorrect urls:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/carlorevelli/Documents/important/code/websockets/node_modules/websocket-as-promised/test/specs/onerror.test.js)
  ```

**Comment by vitalets** [comment]
@frosty00 Are you also on win?

**Comment by vitalets** [comment]
Reproduced issue on windows. `onError` test takes more than 2000 ms there. Committed to master. 

@anton-piliugin @frosty00 could you re-run tests on current master branch?

**Comment by anton-piliugin** [comment]
`onError
    √ should trigger for incorrect urls (2256ms)
    - should trigger by server error`

**Comment by vitalets** [comment]
> `onError`
> ` √ should trigger for incorrect urls (2256ms)`
> ` - should trigger by server error`

Thank you! 👍

**Pull request closed without merging**
